In [6]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()

labels = encoder.fit_transform(items)
print(labels)
print('인코딩 변환값 : ',labels)

[0 1 4 5 3 3 2 2]
인코딩 변환값 :  [0 1 4 5 3 3 2 2]


In [5]:
print('인코딩 클래스 : ', encoder.classes_)

인코딩 클래스 :  ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [10]:
print('디코딩 원본값 : ', encoder.inverse_transform([0,1 ,4 ,5 ,3, 3, 2 ,2]))

디코딩 원본값 :  ['TV' '냉장고' '전자렌지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [26]:
# 원-핫 인코딩

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

from sklearn.preprocessing import OneHotEncoder

oh_encoder = OneHotEncoder()

labels = encoder.fit_transform(items)
labels = labels.reshape(-1,1)
labels

oh_labels = oh_encoder.fit_transform(labels)

print('원-핫 인코딩 : ')
print(oh_labels.toarray())

원-핫 인코딩 : 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [34]:
import pandas as pd

tdf = pd.DataFrame(items)

pd.get_dummies(tdf)

0_TV  0_냉장고  0_믹서  0_선풍기  0_전자렌지  0_컴퓨터
0     1      0     0      0       0      0
1     0      1     0      0       0      0
2     0      0     0      0       1      0
3     0      0     0      0       0      1
4     0      0     0      1       0      0
5     0      0     0      1       0      0
6     0      0     1      0       0      0
7     0      0     1      0       0      0

### 과제
붓꽃 데이터 셋의 독립변수들을 정규화 한 후 평균값과 분산값을 출력하세요.
- 0과 1사이의 범위로 스케일링
- 평균 0 , 표준편차 1인 분포로 스케일링


In [48]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
print(iris.keys())

iris_df = pd.DataFrame(iris.data , columns = iris.feature_names)

iris_df.head()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [50]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [81]:
# MinMaxScaler 로 정규화 0~1 
import numpy as np
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
cols = iris_df.columns

for i in cols:
    iris_df[[i]] = scaler.fit_transform(iris_df[[i]])
    
iris_df

mms_mu = np.mean(iris_df)
mms_var = np.var(iris_df)

print('MinMaxScaler')
print('평균 :\n {} ,\n\n 분산 : \n{}'.format(mms_mu,mms_var))

MinMaxScaler
평균 :
 sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64 ,

 분산 : 
sepal length (cm)    0.052556
sepal width (cm)     0.032763
petal length (cm)    0.088926
petal width (cm)     0.100197
dtype: float64


In [82]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

iris = load_iris()

iris_df = pd.DataFrame(iris.data , columns = iris.feature_names)

ss_scaler = StandardScaler()
cols = iris_df.columns

for i in cols:
    iris_df[[i]] = ss_scaler.fit_transform(iris_df[[i]])
    
iris_df

ss_mu = round(np.mean(iris_df),10)
ss_var = round(np.var(iris_df),10)

print('StandardScaler')
print('평균 : \n{} , \n\n분산 :\n {}'.format(ss_mu,ss_var))

StandardScaler
평균 : 
sepal length (cm)   -0.0
sepal width (cm)    -0.0
petal length (cm)   -0.0
petal width (cm)    -0.0
dtype: float64 , 

분산 :
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
